services:
  - type: web
    name: coded-backend
    runtime: go
    repo: https://github.com/divineshedrack33220/coded
    plan: free
    region: oregon
    buildCommand: cd backend && go build -o main
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true

  - type: mongodb
    name: coded-mongodb
    plan: free
    region: oregon
