services:
  - type: web
    name: coded
    env: go
    plan: free
    repo: https://github.com/divineshedrack33220/coded
    branch: main
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    envVars:
      - key: GO_VERSION
        value: 1.25.5
    rootDir: backend
